# Site settings
title: "Michael Kirlin"
email: "mkirlin@gmail.com"
description: "Personal Site"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: "mike_kirlin"
github_username:  "mkirlin"

# Build settings
markdown: kramdown
